// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class nullableblogIdandprojectIdincomments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullableblogIdandprojectIdincomments));
        
        string IMigrationMetadata.Id
        {
            get { return "202108211441533_nullable-blogId-and-projectId-in-comments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
